name: BasiqFreeze
main: com.basiqnation.basiqfreeze.BasiqFreeze
version: 1.0
author: BasiqDevs
depend: [Vault]
description: Simple way to freeze players
commands:
  freeze:
    description: Freezes target player
    usage:Uasage: /freeze <player>
permissions:
  basiqfreeze.freeze:
    default: op
    description: Freezes target player
