name: BasiqFreeze
main: com.basiqnation.basiqfreeze.BasiqFreeze
version: 0.1
author: BasiqDevs
description: Simple way to freeze players
commands:
  title:
    description: Manage Titles
    usage: /<command> <help>
permissions:
  sgtitles.list:
    default: op
    description: Freezes target player
