name: BasiqFreeze
main: com.basiqnation.basiqfreeze.BasiqFreeze
version: 0.8
author: BasiqDevs
description: Simple way to freeze players
commands:
  freeze:
    description: Freezes target player
    usage:Uasage: /freeze <player>
permissions:
  basiqfreeze.freeze:
    default: op
    description: Freezes target player
